### ISSUE TITLE
[WEB][Settings] In General setting add following fields

### ISSUE THREAD

**Issue by paramanandapradhan** [crawlinknetworks/crawlink-erp#133]
Add following setting after SMS Short Code:
Billing Name : 
Billing Address :
TAX ID or GST : 
Contact Person Name:
Contact Person Phone:
Contact Person Email:

Fields are:
    billingName:String,
    billingAddress:String,
    taxId:String,
    contactName:String,
    contactEmail:String,
    contactPhone:String,

**Comment by urmadhan** [comment]
Added
