### ISSUE TITLE
staff my leave : approval name displayed wrong

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#137]
approval name is displaying the name of one who is applying leave

![Screenshot (45)](https://user-images.githubusercontent.com/54258985/64337438-00e20a00-cffd-11e9-9c91-348fdcf2598c.png)

**Comment by srikanth340** [comment]
Issue fixed

**Comment by urmadhan** [comment]
Not Fixed

**Comment by srikanth340** [comment]
Because of conflict old code is replaced with new code that's why issue exists.

**Comment by urmadhan** [comment]
Fixed
