### ISSUE TITLE
staff leave : created leave is not displayed

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#138]
if a staff created leave and assigned to some other staff , that staff is not getting leaves,
 this issue is not present in all staff ,present in some staff

**Comment by srikanth340** [comment]
issue fixed.

**Comment by urmadhan** [comment]
Not Fixed

**Comment by srikanth340** [comment]
Not observed in dev server

**Comment by urmadhan** [comment]
fIXED
