### ISSUE TITLE
visitor book : edit visitor is not working

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#144]
click on edit visitor

- text fields data is not displayed

![Screenshot (46)](https://user-images.githubusercontent.com/54258985/64505554-dbe9e180-d2f1-11e9-8648-8e48e60a28c1.png)
![Screenshot (47)](https://user-images.githubusercontent.com/54258985/64505555-dbe9e180-d2f1-11e9-9274-b81090e3a71e.png)

**Comment by srikanth340** [comment]
issue fixed

**Comment by urmadhan** [comment]
Fixed
