### ISSUE TITLE
bio-metric attendance : download full attendance , user type column is empty in excel sheet

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#152]
after downloading excel sheet ,user type column is empty in excel sheet,

![Screenshot (49)](https://user-images.githubusercontent.com/54258985/64608786-09658680-d3e9-11e9-97d1-345883888cd2.png)

**Comment by srikanth340** [comment]
Issue is not observed please retest it

**Comment by urmadhan** [comment]
Fixed
