### ISSUE TITLE
bio-metric attendance : column visibility not working properly

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#153]
set default column selection , table is not correct
scroll bar issue

![Screenshot (51)](https://user-images.githubusercontent.com/54258985/64609210-0d45d880-d3ea-11e9-8d7c-c1c48cb2086c.png)
![Screenshot (52)](https://user-images.githubusercontent.com/54258985/64609212-0d45d880-d3ea-11e9-8c2e-784486903343.png)

**Comment by Bharath-S1993** [comment]
Not observed

**Comment by Bharath-S1993** [comment]
Not Observed
