### ISSUE TITLE
Delete and Active options for users

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#16]
**Description** : Delete and active options has to add in users table and details.
**Usage** : Users can delete if we want.
Users can active or deactivate if we want.

**Comment by srikanth340** [comment]
Implemented the active and In-active in users table and details. Added the delete option in user details page. 
Active to make user active.
In-Active to make user In-active
Delete to delete the user from organisation.

**Comment by urmadhan** [comment]
delete is not added in staff

![Screenshot (15)](https://user-images.githubusercontent.com/54258985/63420905-48756d00-c425-11e9-8b1c-d1ec184542ff.png)

**Comment by srikanth340** [comment]
Provided the delete option in staff details.
