### ISSUE TITLE
[web] Finance issues

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#160]
✔1.Receive no has to be changed to receipt no in receive.
✔2.Receipt no should come in sequential order (has to check) (checked by madhan)[dev]
✔3.Student details has to provide 
✔4.Some issue in fee structure .(has to check). 
✔5.For some fees due date colour is not changing in fee schedule and fine is also not calculating .[production]
✔6.For partially paid fee fine amount calculation is wrong.[production]
7. fine is not calculating if you change due date or fine days.[production]
8. if u collect fees partially , for next collection fine amount displayed same as previous.[production]
9. partially paid fee schedule edit discount has to be disable [production].
10. percentage fine amount is not calculating properly, if u collect fee partially..[production]
11. fee schedule excel sheet discount ,fine total amount is undefined .[production].
12. fee schedule edit discount is not working. .[production]
13 Receipt number is not in sequence order. .[production]
14. while collecting fee it is taking more than 2 clicks to save,[not always].[production]

**Comment by srikanth340** [comment]
7. fine is not calculating if you change due date or fine days.[production] [Fixed and provided the edit fine option]
8. if u collect fees partially , for next collection fine amount displayed same as previous.[production] [Provided the edit fine option]

9. partially paid fee schedule edit discount has to be disable [production].[fixed]
10. percentage fine amount is not calculating properly, if u collect fee partially..[production] [not a issue]
11. fee schedule excel sheet discount ,fine total amount is undefined .[production]. [Fixed}
12. fee schedule edit discount is not working. .[production][retest]
13 Receipt number is not in sequence order. .[production][retest]
14. while collecting fee it is taking more than 2 clicks to save,[not always].[production][retest]

**Comment by urmadhan** [comment]
- changed due date is not reflecting in collection

- edited fine amount is not saved.
1. edit fine and save 
2. refresh page edited fine amount is not displayed

11 = not fixed

- edit percentage fine amount calculation is wrong

**Comment by srikanth340** [comment]
**changed due date is not reflecting in collection** : It is not a issue because due date is reflect based on feeschedule not based on fee. If fee schedule doesn't have the due date then it will take from the fee. we can edit the due date in student details or fee schedule list.

**edited fine amount is not saved.** : It will save once after payment is done. Otherwise it won't save the fine changes.

**Issue no 11:** This issue is fixed after deploy only tester will get the changes.

**edit percentage fine amount calculation is wrong** : The fine percentage is calculating for remaining balance and that calculation is correct.
