### ISSUE TITLE
Hostel : view hostel is not working

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#167]
view hostel page is not displayed, error displayed
![Screenshot (55)](https://user-images.githubusercontent.com/54258985/64757433-ca057a00-d54f-11e9-9217-80a9cb936b3f.png)

**Comment by srikanth340** [comment]
Cause : Function name is wrong.
Solution : Calling the correct function

**Comment by urmadhan** [comment]
Fixed
