### ISSUE TITLE
[WEB][AdminConsole][Biometric] Device list must have more columns 'School Id', 'Epush Name'

### ISSUE THREAD

**Issue by crawlinknetworks** [crawlinknetworks/crawlink-erp#17]
Device list must have more columns 'School Id', 'Epush Name'

Epush Name : is useful for Epush server configuration. 
Epush Name will be : 'crawlink:<schoolId>:<deviceId>' 
eg. Epush Name : crawlink:5c57d788fc246e46bbb550af:5d5a517fe61d4859faeac1c6

**Comment by srikanth340** [comment]
More columns : School id and Epush name are added.

**Comment by urmadhan** [comment]
provided
