### ISSUE TITLE
[bio] Add delete option in bio attendance list

### ISSUE THREAD

**Issue by paramanandapradhan** [crawlinknetworks/crawlink-erp#186]
Add delete option in bio attendance from list

**Comment by paramanandapradhan** [comment]
router.delete("/api/bio-attendances/:attendanceId", AuthCtrl.checkUserIdToken, BioAttendanceCtrl.deleteBioAttendance);

**Comment by srikanth340** [comment]
Provided the delete option in attendance list

**Comment by urmadhan** [comment]
added
