### ISSUE TITLE
[web] Delete fee structure and fee

### ISSUE THREAD

**Issue by paramanandapradhan** [crawlinknetworks/crawlink-erp#19]
Delete fee structure and fee from the client.
it should display a warning dialog before send request to server. 
Simply call delete api of respective module. so server will take care of deleting associated records like fee schedules. 

On delete of fee structure, it will delete all fee record, fee schedules, fee receive records ...
On delete of fee it will delete delete fee schedules, fee receive records also. 
Irrespective of single or multi fee receive record, the complete receive record will be deleted.

So, use this delete feature carefully. Show them warning info with impact analysis.

**Comment by paramanandapradhan** [comment]
Implement this feature after #18  closed.

**Comment by srikanth340** [comment]
Delete option is provided for fee structure and fee. Displaying warning message while deleting fee or fee structure. Tested the deletion part in DB.
