### ISSUE TITLE
Fee collection : after editing fine total amount displayed wrong

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#195]
total amount displayed wrong
![Screenshot (59)](https://user-images.githubusercontent.com/54258985/65039045-fca7dc00-d96e-11e9-9160-c8b9c68d212a.png)

**Comment by srikanth340** [comment]
Issue fixed

**Comment by urmadhan** [comment]
not fixed

**Comment by urmadhan** [comment]
Fixed
