### ISSUE TITLE
Communication: Message

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#23]
if there is no message in bottom it is showing load more

**Comment by srikanth340** [comment]
Issue not observed please retest it

**Comment by urmadhan** [comment]
issue present please check it
UI is not correct , title bar is moving

**Comment by srikanth340** [comment]
Load more button will display if more messages are to load other wise it won't display.
when user clicks on load more it will load only 20 records each time.

**Comment by urmadhan** [comment]
changed the button ,Fixed
