### ISSUE TITLE
Staff leave list for approval is not displayed for admin

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#28]
staff leave list for approval is not displayed  for admin 

1. create leave for staff
2. assign to admin 

![Screenshot (3)](https://user-images.githubusercontent.com/54258985/63318090-d15fac00-c332-11e9-9bcf-c7d24c789d69.png)

**Comment by srikanth340** [comment]
Issue fixed . loading data based on assignTo field

**Comment by urmadhan** [comment]
Not fixed issue present

**Comment by srikanth340** [comment]
Issue fixed but because of conflict old code replaced with recent code. That's why issue exists.

**Comment by urmadhan** [comment]
FIXED
