### ISSUE TITLE
staff leave approver and assign to both columns present while staff approving staff leave

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#29]
staff leave approver and assign to both columns present while staff approving staff leave,
assign to column  is empty

![Screenshot (4)](https://user-images.githubusercontent.com/54258985/63318263-88f4be00-c333-11e9-9747-14671dc0d3c7.png)

**Comment by srikanth340** [comment]
From server side assignTo is not populated. that's why assignTo is not displaying.

**Comment by urmadhan** [comment]
Fixed
