### ISSUE TITLE
Fee UI modifications and auto apply

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#30]
**Description** : Make the fee creation as dialog instead of page. Fine creation list has to be in table. If fee structure is applied then newly created fee has to be auto applied to the students. It will make work easy.

**Comment by srikanth340** [comment]
Fee creation page is converted to dialog and fines are implemented using table. Newly created fees are auto applying if fee structure is already applied.

**Comment by urmadhan** [comment]
Fine table UI is not good regarding + anf - part

**Comment by srikanth340** [comment]
Change the plus button to top of the table
![Screenshot from 2019-08-21 18-16-23](https://user-images.githubusercontent.com/54257793/63432979-dfe7b980-c43f-11e9-9b99-47e3ac772230.png)

**Comment by urmadhan** [comment]
Fixed
