### ISSUE TITLE
Display icon for active and in-active in user table

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#31]
**Description** : Display active icon for active and in-active in user table. So user can easily identify it. Green active icon for active user and grey icon for in-active user.

**Comment by srikanth340** [comment]
Displaying the active and in-active icons in user and other school users tables.

**Comment by urmadhan** [comment]
In user bio metric data is active icon is not displayed 

![Screenshot (9)](https://user-images.githubusercontent.com/54258985/63406850-a9427c80-c408-11e9-98f3-8ef713ae570e.png)

**Comment by srikanth340** [comment]
Provided the active and in-active icons in user data.
