### ISSUE TITLE
SMS & Message implementation in details and fee collection

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#38]
**Description** : SMS & Message implementation in user details and fee collection. So that user can send the SMS or message directly to the particular user from there without navigating to communication module. It will make the work simple.

Create two dialogs globally one for SMS and another for message. When user clicks on message or SMS icon open the respective dialog. Then user can fill the fields and send the SMS or message directly.

**Comment by srikanth340** [comment]
SMS and message options are provided in user details and fee collection.
**SMS**: If user has phone number sms automatically takes that number to send the sms. If user doesn't have the phone number the phone number field will be empty.

**Message** : If user clicks on message, automatically it will take the recipient as that selected user and userType to send the message.

**Comment by urmadhan** [comment]
sent sms and msgs are not received .
