### ISSUE TITLE
Add Caste, Gender, Created By, updated By, Updated Date, DoB, DoJ ...(Other Category fields) in Students table filter, and remove Age

### ISSUE THREAD

**Issue by crawlinknetworks** [crawlinknetworks/crawlink-erp#4]
Add Caste, Gender, Created By, updated By, Updated Date, DoB, DoJ ...(Other Category fields) in Students table filter, and remove Age

**Comment by srikanth340** [comment]
Caste, Gender, Created By, updated By, Updated Date, DoB, DoJ are added in staff and student table filter and age is removed.
Based on above options we can filter the users.

**Comment by urmadhan** [comment]
DOB filter is not working

**Comment by srikanth340** [comment]
Not observed this issue DOB filter is not working
