### ISSUE TITLE
Library : In view library, librarians delete option is present 

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#44]
librarians delete option is present in view library but it is not present in edit library

1. click on view library

![Screenshot (6)](https://user-images.githubusercontent.com/54258985/63404340-7c8a6700-c400-11e9-9e20-dce41538334b.png)

**Comment by srikanth340** [comment]
Issue fixed

**Comment by urmadhan** [comment]
Fixed
