### ISSUE TITLE
Staff : In employee list UAN number and PF number columns present but while creating staff those text boxes not present

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#45]
![Screenshot (8)](https://user-images.githubusercontent.com/54258985/63405614-0a685100-c405-11e9-82e3-ee2e557233bc.png)

**Comment by srikanth340** [comment]
Those fields are present in bank details of staff  creation please check it.

**Comment by urmadhan** [comment]
checked.
