### ISSUE TITLE
Fee structure : For single fee, If a class doesn't have students apply is working 

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#48]
create fee of a class which doesn't have students and apply fee

**Comment by srikanth340** [comment]
**Cause** : Null check is not present
**Solution** : Provided the null check

**Comment by urmadhan** [comment]
Not fixed

**Comment by srikanth340** [comment]
**Cause**  Condition wrong while applying the fee
**Solution** corrected the Condition in apply fee
