### ISSUE TITLE
Fee : edit fee structure fields are not disabled

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#49]
![Screenshot (10)](https://user-images.githubusercontent.com/54258985/63408749-60d98d80-c40d-11e9-81df-bda619075b3c.png)

**Comment by srikanth340** [comment]
**Solution :** Making the all fields except name and description are disabled in fee Structure edit part.

**Comment by srikanth340** [comment]
**Cause** : After fee structure is applied then if user creates new fee at that time it is calling the auto apply function there condition is wrong because of it issue occurred. 

**Solution** :Corrected the condition in applyFeeStructure().

**Comment by urmadhan** [comment]
Fixed
