### ISSUE TITLE
Fee : For empty fee list , if you create new fee , there is no fee to apply info msg is displayed

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#50]
1. create fee and apply fee structure 
2. delete fee
3. again create new fee

![Screenshot (11)](https://user-images.githubusercontent.com/54258985/63409498-ea3d8f80-c40e-11e9-99da-61637adfa43d.png)
![Screenshot (12)](https://user-images.githubusercontent.com/54258985/63409500-ea3d8f80-c40e-11e9-9761-5c2695ca2d39.png)

**Comment by srikanth340** [comment]
Duplication of issue no:50

Cause : After fee structure is applied then if user creates new fee at that time it is calling the auto apply function there condition is wrong because of it issue occurred.

Solution :Corrected the condition in applyFeeStructure().

**Comment by urmadhan** [comment]
Fixed
