### ISSUE TITLE
Fee : after creating new fee, created fee is not displayed, but it is displayed after refreshing

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#51]
1. create fee and apply
2. delete fee
3. create new fee

**Comment by srikanth340** [comment]
Cause : After fee structure is applied then if user creates new fee at that time it is calling the auto apply function there condition is wrong because of it issue occurred.

Solution :Corrected the condition in applyFeeStructure().

**Comment by urmadhan** [comment]
Fixed
