### ISSUE TITLE
IsActive and IsAlumni fields has to add in filter

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#54]
**Description** : In filter isActive and isAlumni fields has to add in student list filter and isActive has to add in staff list. So the user can filter users based on requirement. Those two fields should be checkbox.

**Comment by srikanth340** [comment]
IsActive and isAlumni are provided in user filter.

**Comment by urmadhan** [comment]
after selecting Check box, it is going upwards
