### ISSUE TITLE
Examination : Unable to display ERP ID and RF ID in Mark entry

### ISSUE THREAD

**Issue by urmadhan** [crawlinknetworks/crawlink-erp#62]
1. create exam 
2. create entry
3. click on mark entry

![Screenshot (19)](https://user-images.githubusercontent.com/54258985/63430315-e8d58c80-c439-11e9-9601-ae1c9ce5440e.png)

**Comment by srikanth340** [comment]
Unable to observe this issue please test it again.

**Comment by urmadhan** [comment]
issue is present
