### ISSUE TITLE
Biometric: User data download

### ISSUE THREAD

**Issue by crawlinknetworks** [crawlinknetworks/crawlink-erp#7]
User data download option in sidebar
Combine Student and Staff in Filter option.

**Comment by srikanth340** [comment]
User data download option is provided. It is used to download the users for bio-metric device.
we can download the data based on students or staffs or all users. After downloading the data we can upload this data to bio-metric device. User data can be filtered based on conditions and can be search by name, refid, erpid, regNo, email and phone number.
