### ISSUE TITLE
[Web] Finance implementations

### ISSUE THREAD

**Issue by srikanth340** [crawlinknetworks/crawlink-erp#83]
✔1.In receive & payment print option has to provide.
✔2.Fee schedules list based on filter.
✔3.Student fee discount calculation based on target amount.
✔4.Message and filter option in fee schedules list.
✔5.In fee schedule view fee option
✔6.Add fee structure  or fee for a particular student in student details. 
✔7.delete particular fee for student.
8.Search API integration for feeschedules list

**Comment by urmadhan** [comment]
provided
